// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { TokenType } from "./../Common.sol";

/**
 * @title ISpawnSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ISpawnSystem {
  function spawnPlayer() external;

  function buyInfantry(uint256 amount) external;

  function buyInfantryByToken(TokenType token_type, uint256 amount) external;

  function buyCavalryA(uint256 amount) external;

  function buyCavalryB(uint256 amount) external;

  function buyCavalryC(uint256 amount) external;

  function spawnCapital(uint16 capital_id) external payable;

  function garrison(uint16 capital_id, uint256 infantry, uint256 cavalryA, uint256 cavalryB, uint256 cavalryC) external;

  function march(
    uint16 destination,
    uint256 infantry,
    uint256 cavalryA,
    uint256 cavalryB,
    uint256 cavalryC,
    uint8 army_id
  ) external;

  function attack(uint8 army_id) external;

  function farming(uint16 capital_id) external;

  function getStageOneEndTime() external pure returns (uint256 timestamp);
}
