// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IStableSwapSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IStableSwapSystem {
  function swapA2B(uint256 amount) external;

  function swapA2C(uint256 amount) external;

  function pause() external;

  function unpause() external;

  function withdrawToken(address tokenAddress, uint256 amount) external;
}
