// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ITokenManagerSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ITokenManagerSystem {
  function initAllow() external;

  function UltraMintB(uint256 net_value) external;

  function calculateLPAddress() external view returns (address);
}
