/* Autogenerated file. Manual edits will not be saved.*/

#nullable enable
using System;
using System.Linq;
using mud;
using UniRx;
using Property = System.Collections.Generic.Dictionary<string, object>;

namespace mudworld
{
    public class CapitalExtendsTable : MUDTable
    {
        public class CapitalExtendsTableUpdate : RecordUpdate
        {
            public string? Owner;
            public string? PreviousOwner;
        }

        public readonly static string ID = "CapitalExtends";
        public static RxTable Table
        {
            get { return NetworkManager.Instance.ds.store[ID]; }
        }

        public override string GetTableId()
        {
            return ID;
        }

        public string? Owner;

        public override Type TableType()
        {
            return typeof(CapitalExtendsTable);
        }

        public override Type TableUpdateType()
        {
            return typeof(CapitalExtendsTableUpdate);
        }

        public override bool Equals(object? obj)
        {
            CapitalExtendsTable other = (CapitalExtendsTable)obj;

            if (other == null)
            {
                return false;
            }
            if (Owner != other.Owner)
            {
                return false;
            }
            return true;
        }

        public override void SetValues(params object[] functionParameters)
        {
            Owner = (string)functionParameters[0];
        }

        public static IObservable<RecordUpdate> GetCapitalExtendsTableUpdates()
        {
            CapitalExtendsTable mudTable = new CapitalExtendsTable();

            return NetworkManager.Instance.sync.onUpdate
                .Where(update => update.Table.Name == ID)
                .Select(recordUpdate =>
                {
                    return mudTable.RecordUpdateToTyped(recordUpdate);
                });
        }

        public override void PropertyToTable(Property property)
        {
            Owner = (string)property["owner"];
        }

        public override RecordUpdate RecordUpdateToTyped(RecordUpdate recordUpdate)
        {
            var currentValue = recordUpdate.CurrentRecordValue as Property;
            var previousValue = recordUpdate.PreviousRecordValue as Property;
            string? currentOwnerTyped = null;
            string? previousOwnerTyped = null;

            if (currentValue != null && currentValue.ContainsKey("owner"))
            {
                currentOwnerTyped = (string)currentValue["owner"];
            }

            if (previousValue != null && previousValue.ContainsKey("owner"))
            {
                previousOwnerTyped = (string)previousValue["owner"];
            }

            return new CapitalExtendsTableUpdate
            {
                Table = recordUpdate.Table,
                CurrentRecordValue = recordUpdate.CurrentRecordValue,
                PreviousRecordValue = recordUpdate.PreviousRecordValue,
                CurrentRecordKey = recordUpdate.CurrentRecordKey,
                PreviousRecordKey = recordUpdate.PreviousRecordKey,
                Type = recordUpdate.Type,
                Owner = currentOwnerTyped,
                PreviousOwner = previousOwnerTyped,
            };
        }
    }
}
