/* Autogenerated file. Manual edits will not be saved.*/

#nullable enable
using System;
using System.Linq;
using mud;
using UniRx;
using Property = System.Collections.Generic.Dictionary<string, object>;

namespace mudworld
{
    public class GlobalConfigTable : MUDTable
    {
        public class GlobalConfigTableUpdate : RecordUpdate
        {
            public System.Numerics.BigInteger? UnStakeFee;
            public System.Numerics.BigInteger? PreviousUnStakeFee;
            public System.Numerics.BigInteger? PassiveUnStakeFee;
            public System.Numerics.BigInteger? PreviousPassiveUnStakeFee;
            public string? Owner;
            public string? PreviousOwner;
            public string? MerkleRoot;
            public string? PreviousMerkleRoot;
        }

        public readonly static string ID = "GlobalConfig";
        public static RxTable Table
        {
            get { return NetworkManager.Instance.ds.store[ID]; }
        }

        public override string GetTableId()
        {
            return ID;
        }

        public System.Numerics.BigInteger? UnStakeFee;
        public System.Numerics.BigInteger? PassiveUnStakeFee;
        public string? Owner;
        public string? MerkleRoot;

        public override Type TableType()
        {
            return typeof(GlobalConfigTable);
        }

        public override Type TableUpdateType()
        {
            return typeof(GlobalConfigTableUpdate);
        }

        public override bool Equals(object? obj)
        {
            GlobalConfigTable other = (GlobalConfigTable)obj;

            if (other == null)
            {
                return false;
            }
            if (UnStakeFee != other.UnStakeFee)
            {
                return false;
            }
            if (PassiveUnStakeFee != other.PassiveUnStakeFee)
            {
                return false;
            }
            if (Owner != other.Owner)
            {
                return false;
            }
            if (MerkleRoot != other.MerkleRoot)
            {
                return false;
            }
            return true;
        }

        public override void SetValues(params object[] functionParameters)
        {
            UnStakeFee = (System.Numerics.BigInteger)functionParameters[0];

            PassiveUnStakeFee = (System.Numerics.BigInteger)functionParameters[1];

            Owner = (string)functionParameters[2];

            MerkleRoot = (string)functionParameters[3];
        }

        public static IObservable<RecordUpdate> GetGlobalConfigTableUpdates()
        {
            GlobalConfigTable mudTable = new GlobalConfigTable();

            return NetworkManager.Instance.sync.onUpdate
                .Where(update => update.Table.Name == ID)
                .Select(recordUpdate =>
                {
                    return mudTable.RecordUpdateToTyped(recordUpdate);
                });
        }

        public override void PropertyToTable(Property property)
        {
            UnStakeFee = (System.Numerics.BigInteger)property["unStakeFee"];
            PassiveUnStakeFee = (System.Numerics.BigInteger)property["passiveUnStakeFee"];
            Owner = (string)property["owner"];
            MerkleRoot = (string)property["merkleRoot"];
        }

        public override RecordUpdate RecordUpdateToTyped(RecordUpdate recordUpdate)
        {
            var currentValue = recordUpdate.CurrentRecordValue as Property;
            var previousValue = recordUpdate.PreviousRecordValue as Property;
            System.Numerics.BigInteger? currentUnStakeFeeTyped = null;
            System.Numerics.BigInteger? previousUnStakeFeeTyped = null;

            if (currentValue != null && currentValue.ContainsKey("unstakefee"))
            {
                currentUnStakeFeeTyped = (System.Numerics.BigInteger)currentValue["unstakefee"];
            }

            if (previousValue != null && previousValue.ContainsKey("unstakefee"))
            {
                previousUnStakeFeeTyped = (System.Numerics.BigInteger)previousValue["unstakefee"];
            }
            System.Numerics.BigInteger? currentPassiveUnStakeFeeTyped = null;
            System.Numerics.BigInteger? previousPassiveUnStakeFeeTyped = null;

            if (currentValue != null && currentValue.ContainsKey("passiveunstakefee"))
            {
                currentPassiveUnStakeFeeTyped = (System.Numerics.BigInteger)
                    currentValue["passiveunstakefee"];
            }

            if (previousValue != null && previousValue.ContainsKey("passiveunstakefee"))
            {
                previousPassiveUnStakeFeeTyped = (System.Numerics.BigInteger)
                    previousValue["passiveunstakefee"];
            }
            string? currentOwnerTyped = null;
            string? previousOwnerTyped = null;

            if (currentValue != null && currentValue.ContainsKey("owner"))
            {
                currentOwnerTyped = (string)currentValue["owner"];
            }

            if (previousValue != null && previousValue.ContainsKey("owner"))
            {
                previousOwnerTyped = (string)previousValue["owner"];
            }
            string? currentMerkleRootTyped = null;
            string? previousMerkleRootTyped = null;

            if (currentValue != null && currentValue.ContainsKey("merkleroot"))
            {
                currentMerkleRootTyped = (string)currentValue["merkleroot"];
            }

            if (previousValue != null && previousValue.ContainsKey("merkleroot"))
            {
                previousMerkleRootTyped = (string)previousValue["merkleroot"];
            }

            return new GlobalConfigTableUpdate
            {
                Table = recordUpdate.Table,
                CurrentRecordValue = recordUpdate.CurrentRecordValue,
                PreviousRecordValue = recordUpdate.PreviousRecordValue,
                CurrentRecordKey = recordUpdate.CurrentRecordKey,
                PreviousRecordKey = recordUpdate.PreviousRecordKey,
                Type = recordUpdate.Type,
                UnStakeFee = currentUnStakeFeeTyped,
                PreviousUnStakeFee = previousUnStakeFeeTyped,
                PassiveUnStakeFee = currentPassiveUnStakeFeeTyped,
                PreviousPassiveUnStakeFee = previousPassiveUnStakeFeeTyped,
                Owner = currentOwnerTyped,
                PreviousOwner = previousOwnerTyped,
                MerkleRoot = currentMerkleRootTyped,
                PreviousMerkleRoot = previousMerkleRootTyped,
            };
        }
    }
}
