/* Autogenerated file. Manual edits will not be saved.*/

#nullable enable
using System;
using System.Linq;
using mud;
using UniRx;
using Property = System.Collections.Generic.Dictionary<string, object>;

namespace mudworld
{
    public class PlayerDetailTable : MUDTable
    {
        public class PlayerDetailTableUpdate : RecordUpdate
        {
            public System.Numerics.BigInteger? Gold;
            public System.Numerics.BigInteger? PreviousGold;
            public System.Numerics.BigInteger? Infantry;
            public System.Numerics.BigInteger? PreviousInfantry;
            public System.Numerics.BigInteger? Cavalry;
            public System.Numerics.BigInteger? PreviousCavalry;
            public uint? Capital;
            public uint? PreviousCapital;
        }

        public readonly static string ID = "PlayerDetail";
        public static RxTable Table
        {
            get { return NetworkManager.Instance.ds.store[ID]; }
        }

        public override string GetTableId()
        {
            return ID;
        }

        public System.Numerics.BigInteger? Gold;
        public System.Numerics.BigInteger? Infantry;
        public System.Numerics.BigInteger? Cavalry;
        public uint? Capital;

        public override Type TableType()
        {
            return typeof(PlayerDetailTable);
        }

        public override Type TableUpdateType()
        {
            return typeof(PlayerDetailTableUpdate);
        }

        public override bool Equals(object? obj)
        {
            PlayerDetailTable other = (PlayerDetailTable)obj;

            if (other == null)
            {
                return false;
            }
            if (Gold != other.Gold)
            {
                return false;
            }
            if (Infantry != other.Infantry)
            {
                return false;
            }
            if (Cavalry != other.Cavalry)
            {
                return false;
            }
            if (Capital != other.Capital)
            {
                return false;
            }
            return true;
        }

        public override void SetValues(params object[] functionParameters)
        {
            Gold = (System.Numerics.BigInteger)functionParameters[0];

            Infantry = (System.Numerics.BigInteger)functionParameters[1];

            Cavalry = (System.Numerics.BigInteger)functionParameters[2];

            Capital = (uint)functionParameters[3];
        }

        public static IObservable<RecordUpdate> GetPlayerDetailTableUpdates()
        {
            PlayerDetailTable mudTable = new PlayerDetailTable();

            return NetworkManager.Instance.sync.onUpdate
                .Where(update => update.Table.Name == ID)
                .Select(recordUpdate =>
                {
                    return mudTable.RecordUpdateToTyped(recordUpdate);
                });
        }

        public override void PropertyToTable(Property property)
        {
            Gold = (System.Numerics.BigInteger)property["gold"];
            Infantry = (System.Numerics.BigInteger)property["infantry"];
            Cavalry = (System.Numerics.BigInteger)property["cavalry"];
            Capital = (uint)property["capital"];
        }

        public override RecordUpdate RecordUpdateToTyped(RecordUpdate recordUpdate)
        {
            var currentValue = recordUpdate.CurrentRecordValue as Property;
            var previousValue = recordUpdate.PreviousRecordValue as Property;
            System.Numerics.BigInteger? currentGoldTyped = null;
            System.Numerics.BigInteger? previousGoldTyped = null;

            if (currentValue != null && currentValue.ContainsKey("gold"))
            {
                currentGoldTyped = (System.Numerics.BigInteger)currentValue["gold"];
            }

            if (previousValue != null && previousValue.ContainsKey("gold"))
            {
                previousGoldTyped = (System.Numerics.BigInteger)previousValue["gold"];
            }
            System.Numerics.BigInteger? currentInfantryTyped = null;
            System.Numerics.BigInteger? previousInfantryTyped = null;

            if (currentValue != null && currentValue.ContainsKey("infantry"))
            {
                currentInfantryTyped = (System.Numerics.BigInteger)currentValue["infantry"];
            }

            if (previousValue != null && previousValue.ContainsKey("infantry"))
            {
                previousInfantryTyped = (System.Numerics.BigInteger)previousValue["infantry"];
            }
            System.Numerics.BigInteger? currentCavalryTyped = null;
            System.Numerics.BigInteger? previousCavalryTyped = null;

            if (currentValue != null && currentValue.ContainsKey("cavalry"))
            {
                currentCavalryTyped = (System.Numerics.BigInteger)currentValue["cavalry"];
            }

            if (previousValue != null && previousValue.ContainsKey("cavalry"))
            {
                previousCavalryTyped = (System.Numerics.BigInteger)previousValue["cavalry"];
            }
            uint? currentCapitalTyped = null;
            uint? previousCapitalTyped = null;

            if (currentValue != null && currentValue.ContainsKey("capital"))
            {
                currentCapitalTyped = (uint)currentValue["capital"];
            }

            if (previousValue != null && previousValue.ContainsKey("capital"))
            {
                previousCapitalTyped = (uint)previousValue["capital"];
            }

            return new PlayerDetailTableUpdate
            {
                Table = recordUpdate.Table,
                CurrentRecordValue = recordUpdate.CurrentRecordValue,
                PreviousRecordValue = recordUpdate.PreviousRecordValue,
                CurrentRecordKey = recordUpdate.CurrentRecordKey,
                PreviousRecordKey = recordUpdate.PreviousRecordKey,
                Type = recordUpdate.Type,
                Gold = currentGoldTyped,
                PreviousGold = previousGoldTyped,
                Infantry = currentInfantryTyped,
                PreviousInfantry = previousInfantryTyped,
                Cavalry = currentCavalryTyped,
                PreviousCavalry = previousCavalryTyped,
                Capital = currentCapitalTyped,
                PreviousCapital = previousCapitalTyped,
            };
        }
    }
}
