// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Player } from "./tables/Player.sol";
import { PlayerDetail, PlayerDetailData } from "./tables/PlayerDetail.sol";
import { Army, ArmyData } from "./tables/Army.sol";
import { Capital, CapitalData } from "./tables/Capital.sol";
import { BattleReport, BattleReportData } from "./tables/BattleReport.sol";
import { GlobalStatistics, GlobalStatisticsData } from "./tables/GlobalStatistics.sol";
import { GlobalStake, GlobalStakeData } from "./tables/GlobalStake.sol";
import { GlobalConfig, GlobalConfigData } from "./tables/GlobalConfig.sol";
import { PlayerStake, PlayerStakeData } from "./tables/PlayerStake.sol";
