// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { Player, PlayerTableId } from "./tables/Player.sol";
import { PlayerDetail, PlayerDetailData, PlayerDetailTableId } from "./tables/PlayerDetail.sol";
import { Cite, CiteTableId } from "./tables/Cite.sol";
import { Army, ArmyData, ArmyTableId } from "./tables/Army.sol";
import { Capital, CapitalData, CapitalTableId } from "./tables/Capital.sol";
import { CapitalExtends, CapitalExtendsTableId } from "./tables/CapitalExtends.sol";
import { Toad, ToadTableId } from "./tables/Toad.sol";
import { Position, PositionData, PositionTableId } from "./tables/Position.sol";
import { GameManager, GameManagerTableId } from "./tables/GameManager.sol";
